### ISSUE TITLE
Compilation error in VSC+PlarformIO...

### ISSUE THREAD

**Issue by AlexArGC** [JChristensen/JC_EEPROM#1]
Jack, first of all, thank you very much for the idea of ​​using the `reinterpret_cast` function! However, many write that we are violating the C++ standard. I used pointers and `memcpy()` :-) Your solution looks more elegant!

Thank you for reviving the topic and updating the description of your library!

There are compilation errors in other development environments than the Arduino IDE. PlatformIO+Framework+Arduino+Espressif 32 in the wire.h library doesn't have the variables you're referring to.
```
'TWBR' was not declared in this scope
'BUFFER_LENGTH' was not declared in this scope
```
In the first case, you can simply define an "empty" variable...
In the second one in the Wire.h library ()
`#define I2C_BUFFER_LENGTH 128`

P.S.
I remember asking questions not about salary :-)
It fixes quickly, but your last example worked without errors.

**Comment by JChristensen** [comment]
Hello again Alexander,

1. Please explain, in what way is the C++ standard violated.

2. This library no longer references TWBR. Please check to ensure you are using the correct library.

3. I may have a fix for the BUFFER_LENGTH issue, but please let me hear from you on the other points first.

Cheers ... Jack

**Comment by AlexArGC** [comment]
1. This is called "undefined behavior". In my case, I do not see big risks, even breaking this rule. But if you go into details, then http://eel.is/c++draft/basic.lval#10

2. Guilty! PlatformIO automatically pulled up version 1.0.1, although there is 1.0.2 in the changelog (I will update manually). Maybe there is an error in the properties of the library description?

3. Thank you for your feedback. 

![изображение](https://user-images.githubusercontent.com/48761297/152842611-e5503c43-3c42-44ee-b61e-5b40321987a2.png)

```
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html
PLATFORM: Espressif 32 (3.4.0) > DOIT ESP32 DEVKIT V1
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10006.210326 (1.0.6)
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing jchristensen/JC_EEPROM @ ^1.0.2
Warning! Could not find the package with 'jchristensen/JC_EEPROM @ ^1.0.2' requirements for your system 'windows_amd64'
```

**Comment by JChristensen** [comment]
1. Is that in regard to using `reinterpret_cast`? Even if I set Compiler warnings to "All," the compiler does not complain. Indeed `reinterpret_cast` should be used carefully, but I think this usage is acceptable.
2. Interesting, it appears that the Arduino library index has not picked up 1.0.2 either, although library.properties looks fine. I'll look into it!
3. Standby for a fix. Pushing a new version may fix the previous problem too.

**Comment by AlexArGC** [comment]
> 

Thanks!
It's not a problem, you just want your library to look nice!

Maybe you will think ... Bring `reinterpret_cast` inside the functions `write `and `read`.
Then you can completely get rid of types, and pass any reference to a variable, array or structure :-)

**Comment by JChristensen** [comment]
> Maybe you will think ... Bring `reinterpret_cast` inside the functions `write `and `read`.
> Then you can completely get rid of types, and pass any reference to a variable, array or structure :-)

So then we could have 
```c++
byte write(unsigned long addr, void* values, unsigned int nBytes);
```

**Comment by AlexArGC** [comment]
Updated to version 1.0.2
Compiler issues 1 warning
`ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: [131, 41]`

to a line of code 
`Wire.requestFrom(ctrlByte, nRead);`

> So then we could have
> 
> ```c++
> byte write(unsigned long addr, void* values, unsigned int nBytes);
> ```

`unsigned int nBytes` can you calculate the functions inside?

**Comment by JChristensen** [comment]
> Updated to version 1.0.2
> Compiler issues 1 warning

What board are you compiling for?

**Comment by AlexArGC** [comment]
> > Updated to version 1.0.2
> > Compiler issues 1 warning
> 
> What board are you compiling for?

See above https://github.com/JChristensen/JC_EEPROM/issues/1#issuecomment-1031738463

**Comment by JChristensen** [comment]
Probably need to change variables to fixed-width integers. Stand by. Want to make sure the Arduino index is picking up changes first.

**Comment by AlexArGC** [comment]
> Probably need to change variables to fixed-width integers. Stand by. Want to make sure the Arduino index is picking up changes first.

Version 1.0.1 has become available :-)))))) 

https://docs.platformio.org/en/latest//core/userguide/lib/cmd_install.html?utm_source=platformio&utm_medium=piohome

**Comment by JChristensen** [comment]
Should also have 1.0.3 now.

**Comment by AlexArGC** [comment]
> Should also have 1.0.3 now.

You can try to put it like this in `library.properties`:
`architectures=*`

**Comment by JChristensen** [comment]
> You can try to put it like this in `library.properties`:
> `architectures=*`

I tend not to do that as I only work with AVR architecture. If I can't test or debug on other platforms, I have a hard time advertising as such.

**Comment by JChristensen** [comment]
> Compiler issues 1 warning
> `ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: [131, 41]`

Version 1.0.4 should be available now. Please let me know if it fixes this issue.
I also just pushed 1.0.5 but that just has updates to example sketches and README file.

**Comment by AlexArGC** [comment]
Arduino IDE it`s Ok.

![изображение](https://user-images.githubusercontent.com/48761297/153046169-7acaa47a-277f-4ae7-8de6-2f331561682f.png)

PlatformIO no udpated :-(

![изображение](https://user-images.githubusercontent.com/48761297/153046757-242b61d7-07e3-4550-aebe-51555bb1baf4.png)

**Comment by JChristensen** [comment]
Sounds like PlatformIO has problems then.

Does the latest version address the warning below? If so, can this issue be closed?
```
Compiler issues 1 warning
ISO C++ says that these are ambiguous, even though the worst conversion for the first
is better than the worst conversion for the second: [131, 41]
```

**Comment by AlexArGC** [comment]
> Sounds like PlatformIO has problems then.

There’s no matching 1.0.1 tag for the 1.0.1 version, nor is there a release for it.

If this library had a library.json, that wouldn’t be an issue, as having the[ version ](https://docs.platformio.org/en/latest/librarymanager/config.html#id11)and[ repository ](https://docs.platformio.org/en/latest/librarymanager/config.html#id10)parameters would be enough information for the PlatformIO registry crawler to see there was a new version, and where to get it from. I don’t think the url= field in the Arduino IDE library.properties is sufficient, as it is supposed point to the library homepage, which may not be the Git(Lab|Hub)/other repo.

If there’s a stuck library update, since the library registry is still a manual process, library owner should just make a new post asking for that library to be checked to see what’s stuck! :wink: Right [@ivankravets](https://community.platformio.org/u/ivankravets)?


> Does the latest version address the warning below? If so, can this issue be closed?

Version 1.0.6. compiling no errors.

**Comment by JChristensen** [comment]
I see no issue with either [tags](https://github.com/JChristensen/JC_EEPROM/tags) or [releases](https://github.com/JChristensen/JC_EEPROM/releases) on GitHub; 1.0.1 appears in both. The Arduino library updates are in fact quite automated; further I see no issues in the [logs from the Library indexer](https://downloads.arduino.cc/libraries/logs/github.com/JChristensen/JC_EEPROM/). I don't use PlatformIO and since things look fine in the Arduino IDE and on GitHub, I do not have time to be concerned about it. Sorry.

Closing this issue now. I will consider using void pointers in the future as an enhancement but that will have to come after some other priorities. Thanks for all your input, I hope you have great day!
