### ISSUE TITLE
How to customize the pins of I2C?

### ISSUE THREAD

**Issue by murarduino** [JChristensen/JC_EEPROM#2]
I plan to use pin 25 of ESP32 to define SDA and pin 26 to define SCL,

Can I modify it like this in JC_EEPROM.cpp?

uint8_t JC_EEPROM::begin(twiClockFreq_t twiFreq)
{
    Wire.begin(25,26);
    Wire.setClock(twiFreq);
    Wire.beginTransmission(m_eepromAddr);
    if (m_nAddrBytes == 2) Wire.write(0);   // high addr byte
    Wire.write(0);                          // low addr byte
    return Wire.endTransmission();
}

**Comment by JChristensen** [comment]
Sorry, I'm not very familiar with ESP32, I've only used this library with AVR.
