### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by Manhem** [JChristensen/JC_EEPROM#3]
hi.
This is not an issue, but I would like to have an example over one thing that I can't understand.
I'm using a M24M02 memory.
I only write byte at the time when I'm saving something.
So how can I erase the entire memory as fast as posible?
And also how do I write only one byte, let's say at the higher end of the memory?

It's a great job you have done here, thanks.

**Comment by JChristensen** [comment]
Greetings,

Thanks for the kind words, I am glad that you like the library.

The [eepromTest example](https://github.com/JChristensen/JC_EEPROM/blob/master/examples/eepromTest/eepromTest.ino) has an erase function. To use it with an M24M02, make the following changes.
Change [line 17](https://github.com/JChristensen/JC_EEPROM/blob/88b0a631e98f74b10b2a2621c9624f632e3db5b2/examples/eepromTest/eepromTest.ino#L17) to:
```c++
JC_EEPROM eep(JC_EEPROM::kbits_2048, 1, 256);
```
Change the constant on [line 19](https://github.com/JChristensen/JC_EEPROM/blob/88b0a631e98f74b10b2a2621c9624f632e3db5b2/examples/eepromTest/eepromTest.ino#L19) to `true`.
Change the constant on [line 21](https://github.com/JChristensen/JC_EEPROM/blob/88b0a631e98f74b10b2a2621c9624f632e3db5b2/examples/eepromTest/eepromTest.ino#L21) to `256`.

To write a single byte anywhere in the EEPROM, use the [write method](https://github.com/JChristensen/JC_EEPROM#writeuint32_t-addr-uint8_t-value). The last address for an M24M02 would be 262143 or 0x3FFFF, e.g.:
```c++
// write the value 42 to EEPROM location 262143
uint8_t i2cStat = eep.write(262143, 42);
```
HTH ... jc
