### ISSUE TITLE
Issue with JC_EEPROM lib.

### ISSUE THREAD

**Issue by 4r53N1ck** [JChristensen/JC_EEPROM#4]
S

**Comment by JChristensen** [comment]
Show us line 101 from your code please.

**Comment by 4r53N1ck** [comment]
`#include <JC_EEPROM.h>

uint32_t datos=0x8393F8;
uint32_t eepromAddress;
uint8_t* buff[4];

JC_EEPROM eep(JC_EEPROM::kbits_32,1,32);

void setup(){
  
  Serial.begin(9600);
  byte i2cStat = eep.begin(JC_EEPROM::twiClock100kHz);
  if ( i2cStat != 0 ) {
    Serial.println(F("I2C Problem"));
  }
  buff[0] = datos;
  buff[1] = datos>>8;
  buff[2] = datos>>16;
  delay(10);
  eep.write(0, &buff, 3);
  Serial.print("0x");
  Serial.print(eep.read(0, &buff, 3),HEX);
  Serial.print('\n');
  Serial.print("0x");
  Serial.print(eepromAddress,HEX);
}

void loop(){
  
}
`

**Comment by JChristensen** [comment]
Does this do what you want?
```c++
#include <JC_EEPROM.h>

uint32_t datos = 0x8393F8;
uint32_t eepromAddress;
uint8_t buff[4];

JC_EEPROM eep(JC_EEPROM::kbits_32, 1, 32);

void setup() {

    Serial.begin(9600);
    byte i2cStat = eep.begin(JC_EEPROM::twiClock100kHz);
    if ( i2cStat != 0 ) {
        Serial.println(F("I2C Problem"));
    }
    buff[0] = datos;
    buff[1] = datos >> 8;
    buff[2] = datos >> 16;
    delay(10);
    eep.write(0, buff, 3);
    Serial.print("0x");
    Serial.print(eep.read(0, buff, 3), HEX);
    Serial.print('\n');
    Serial.print("0x");
    Serial.print(eepromAddress, HEX);
}

void loop() {

}
```

**Comment by 4r53N1ck** [comment]
Yes. Now it compiles. Why is not working with pointers?

**Comment by 4r53N1ck** [comment]
Update: Command "write" is working. Command "read" also working. Now, if you pass eep.write(add, pointer array, bytes) as an argument of Serial.print is not working. It shows 0x0 on the serial monitor.

```
#include <Wire.h>
#include <JC_EEPROM.h>

uint32_t datos=0x8393F8;
uint32_t eepromAddress;
uint8_t buff[4];

JC_EEPROM eep(JC_EEPROM::kbits_32,1,32);

void setup(){
  uint8_t buff1[4];
  Serial.begin(9600);
  byte i2cStat = eep.begin(JC_EEPROM::twiClock100kHz);
  if ( i2cStat != 0 ) {
    Serial.println(F("I2C Problem"));
  }
  buff[0] = datos;
  buff[1] = datos>>8;
  buff[2] = datos>>16;
  delay(10);
  eep.write(0, buff, 3);
  eep.read(0,buff1,3);
  Serial.print("0x");
//  Serial.print(eep.read(0,buff1,3),HEX);    //Not working

//But this works:
  Serial.print(buff1[2],HEX);                 
  Serial.print(buff1[1],HEX);
  Serial.print(buff1[0],HEX);
  Serial.print('\n');
  Serial.print("0x");
  Serial.println(eepromAddress,HEX);
}

void loop(){
  
}
```

**Comment by JChristensen** [comment]
These are not issues with the library, they are issues with your code and your understanding of C++, therefore I am closing this issue.

The [eep.read() function](https://github.com/JChristensen/JC_EEPROM#readuint32_t-addr-uint8_t-values-uint16_t-nbytes) returns a status indicating whether the operation was successful.
Therefore `Serial.print(eep.read())` just prints this status; zero indicates success.
Best regards.

**Comment by 4r53N1ck** [comment]
There is no issue with my understanding of C++, I think I forgot my brain on the market yesterday (the proof is that I called "commands" instead of "functions"), that's why I didn't realize that read() is not a void function and when I pass it as an argument it returns a zero, which is the number that "print" shows. 

Regardless, I can use read function to set the bytes into some array, then show those bytes after through the "print" function.

Many thanks to you, great work with this library!

**Comment by JChristensen** [comment]
OK, sorry about that. Cheers!
