### ISSUE TITLE
Error code documentation?

### ISSUE THREAD

**Issue by dkadrios** [JChristensen/JC_EEPROM#5]
Does anyone have a list of possible error codes?  I'm getting back `4` from `begin()` and I haven't the foggiest what to do.  I tried the documentation linked to from README, but it's a stale link.  I also poked around `wire.h` hoping to find some consts but came up empty.  Please help if you can.  Thanks!

**Comment by JChristensen** [comment]
Thanks, I will update the links. They should point [here](https://www.arduino.cc/reference/en/language/functions/communication/wire/endtransmission/).
Unfortunately [error code 4](https://github.com/arduino/ArduinoCore-avr/blob/eabd762a1edcf076877b7bec28b7f99099141473/libraries/Wire/src/utility/twi.c#L250) is "other twi error (lost bus arbitration, bus error, ..)" so not a lot of help.
I would double check the wiring, etc.

**Comment by dkadrios** [comment]
thank you @JChristensen, I'll keep plugging away.  I think it's something to do with the Teensy 4.0 I'm using having multiple i2c ports and I'm probably not configuring them correctly

**Comment by dkadrios** [comment]
Just to follow up in case anyone else should encounter error code 4 -- in my case, all I had to do was shorten the wires for SDL and SDA and things started working.  It also seems that you do not need pullups on these (for the Teensy 4)

Things are working beautifully for me now -- thank you @JChristensen for providing such a tight library!

**Comment by JChristensen** [comment]
@dkadrios thanks for the feedback and for the kind words.
My rule of thumb is to use 4.7k pullups for 100kHz I2C bus speed, and 2.2k for 400kHz. These seem to work well for bus lengths of several inches, even in messy breadboard situations.
That shortening the wires got things working may indicate that stronger (i.e. lower value) pullups are needed. The internal pullups in many microcontrollers are typically much higher value, e.g. 20-50k for AVR MCUs.
