### ISSUE TITLE
Compilation error      error: 'kbits_1024' was not declared in this scope

### ISSUE THREAD

**Issue by mackelec** [JChristensen/JC_EEPROM#7]
my compilation error
DUEbms_20231025:10:20: error: 'kbits_1024' was not declared in this scope

Arduino IDE 1.8.19   target :DUE

```
#include <JC_EEPROM.h>
#include <can_common.h>
#include <due_can.h>
#include <PString.h>
#include <Streaming.h>
#include <SPI.h>
#include "mcp_can.h"
//#include <extEEPROM.h>


JC_EEPROM myEEPROM(kbits_1024, 1, 256); 
//extEEPROM eep(kbits_1024, 1, 256); 

```

I clearly see it is defined.
your example code does work!!    even if I include all the  libraries I use.
It's a large project so It's difficult to remove the other libraries from my project.

However your old library does compile without giving me errors.

I'm not saying JC_EEPROM has a problem, especially considering you example code works.
I hope this is useful.

**Comment by mackelec** [comment]
FYI, the version of extEEprom  is version=3.4.1

**Comment by JChristensen** [comment]
The correct constant to use is `JC_EEPROM::kbits_1024` not just `kbits_1024`
[extEEPROM](https://github.com/PaoloP74/extEEPROM) is not my library. It's a fork of my library.

**Comment by mackelec** [comment]
Couldn't see the trees for the forest - yes, all good thanks
