### ISSUE TITLE
JC_EEPROM successfully running on an ESP-12F/ESP8266...

### ISSUE THREAD

**Issue by dl9sec** [JChristensen/JC_EEPROM#8]
Hi Jack,
just want to let you know, that I have your JC_EEPROM library successfully running on an ESP-12F/ESP8266 together with an AT24C02 EEPROM.
So maybe you can add this to "architectures" in the "library.properties" file.

Thank you.

Regards, Thorsten

**Comment by JChristensen** [comment]
Thanks, Thorsten. Nice to hear from Germany.
Merry Christmas and Happy New Year from Michigan, USA.
